branches:
  only:
  - master
  - stable
language: java
env:
  global:
  - secure: L7WetnE0APcOLAqto4TtW+ry9NRRI7WisglbcCeDg0XE2QOAeqHP4mPCjWPhmXJ5Eo2NZ/hF6trCycDlub9jIJzXqC5dDjw0Cc2w7WfvfJbZWrP4NC5p8UvILCdgLL2iV191CekKqyIqnjDCV1XIevdCilbaq2eceQFtg+A12a3C6J311CcZPgxkMpmTYOirAL0FzQndL/Rn5D87cQrlcXwybN3vW7lH92NHy2AIkjsmOLZ3O9Rn/2ZU3xsCjlqig2BSUsAyI2nuqhQVpEqicmi0QqZWTz6LiAU2Fjy+RG1qETecLacVPlq3nStiXdY5fv9iF7ymnn2Fqf0gLGTm1A1sQJtAfR+rxe2DCSR4Tj0E1N1U15mIefsNdJ6l5QdrqorOoKGMjlMrPND8KICC+GlF54rRJjxEduF5iFXPWGoApegEy9XDEivJEMTPQ036B0W59UP9MGfkGD4WWCTafsOMGizB29H+GQiClhVipPAkj6+LYrduJ2bXIgUuQcrCKxw7LRwFYzPSKjMkydSKPuZ+6gVe8De9KIVgCti9BeB+MLL0B+PcQyu7dRG4SkFynUyQe+l5Pj6ZEnkAYowye7hlUl6/zp58FeCT8/I/92G/A0Hr9p1LiSNTIn7GUf+WkC3bbNSyu/HZ8Tl5zytWca6/Wa6N+lBfLIBw0CR610s=
  - secure: Kv78OTYYvhWE6/oCyyIFEH+8W8s2UD4r62SIxVsNrLSNSdg/Nb3BN5O7PmGc+LO4fOZ1Sw6WtsxnGsa85ajWtTsr/qCa3P7N0NUrYt0aDXWYZWOvkobnJdBEzH7tZZnJW1ZEbLKGWzdidHuzhGn2XXd7L2+1x7UODd/YT+eII31hLlQngIeimd07ns0UkPtWxoC6aRtzibf3YdG3aGHYIGzoI/MplyLzUBjHjvZM/IvD6d7M3G1Fm9zHs46soT2SpueVY1aQXw78KhZsiVAAbcioWp+UVmcrDDL4jNeAzc/UvrOTYCyN1PBLCU5mZb8O3Zm7W/oUnpApsXf+MZXTuPU9f3vZf1mE8JyBMzHW0y3HMe7IQ3OzU+J/s8M9gijIletXNexeA9v/dN5wMj7XzAWpOchHv/0G8/mL2FXnjGZhyOWgviRRxqyDZwZDDjpMxx2QEo4xwo2XAIFt9n6h+pNgtwQJqhf6iwtjkeGnGAHrEp7PGcvrUATqJMTrHdoc8Ogxv73lCHRCqKDBuTmAdfEfUyIqXV1HYAyn+Xw68Z4r1jECf4btoyNRiUiU+UHcUTQIU3SJ49d2rBnUdXPVVsDj1NvelY37GZsT+Ch3Nrzb+n9EsiLQ5xEyxv+Le3L2Qj19z3V1ujRlv8tYiElr4cmDSdBfq+fvmTmtH7wepWM=
  - secure: pTJGfQ7qgbhihttqeSg2GLTWIvnBK+HSMwdl436gc4bs7aPt/9lsdxpLqc208SHVp7k2N9fBOM9Tzq0apdPAngO6GefaozJLyaziZdYqo/Sld7AB6b3AV+algfqz2xwUOZZOz1dQGQnVhTFpw8aC4718xJN26UOEf/mbRCfp0V++2ZrKleeKmRLXoyiFFsDhIk1FNDS0eqZNL2+eBaV1QNRvi12i/BTI6bezRJarhqjS+tUM3FPuDawF32n4gLmdjbNk9AdB0ogMxvZQ+0GmdwoXZWJHnXx09P/dNeUXoR9XFGRQGff5gbt/uPR9AiCok8cJy2xjTWLlmdJ7G9PLJfMfUqS2yrD2wb+/M0lb/w2I0KZ+Z8js47ckz5eheUpsQ37rr3KZUmtmNxoNlMJbT34sFknhve/7pD24kX6kIW3fltBoO4uo3PKwhN+r52pLRHkMuhm9Wdwx/5E5kK2w/9qnQ4SMLEy1xe74U4VaSyJrUjSjaNBsu+jPNC99Yfx0oAz2f9WeYDpli8Z/cENJtLwo30eX+Y3+49ua5nk81623k291ZgEvOCBdQyr14xULtyT3Xy8YB4dFpsxkDeYr4llG6C/BMAJAAhCdKt2A0Ib/IIVoLbZwdA3VP1sQCOZUa7cKZ2BCDxSq96YZMaKYGP3iaJx9wwXy3NdEtQUhV3Y=
  - secure: vKgUHk2o+eI90l5I82xz+90yzZ1++cXXtNINqrpvvLjphv2O6Vx/BXz5NtW8UFHEJ6NIQwzKGqIrrDcKI+bAeQlJBa2vh3LPXe/0rsCMSdfxko82e9nqumeMD4OcD+leP7hS5Sb7MR8DmRV9ILakK7nhtPBOiZ2XXg0Uj5aEVFaELzqDzgicinHvUVSRmRDO7TxhxkX+3DoIzOZTdqOwemNeGElytWbaIq6UoN1rkumE+XxSrnuavP7pgyr2H7FTA8Eols/RPP8v7qvi0WXWq4zz3Q3zS8LFUhDsIrGIjcYu9p00Rj9z+ARm9bT5Eity5LEJ6VZDDkYLNRCsXmtx7gLwm3z5OO6ms/YaBpN1h9wMasU8P20Ae0Xeh5POeGLjpbwuk1gNtEdY95rjeC5c7u8FFBmgrLgU3N5K8YyZeRh12+ig9drTCbSNbmXZo0s6udwXwaEnKJHez8vpZ5HQh1a7Mke1P6FyTL8VPSg8qVkMyZYGeui9bUwBvoOVGgBgthmnyx53H1EKvp1xvgnRay7SPJ1IS/QuOHkJZT2EM8xrXMwuecqXc4isnRr2ex0TiQIGhCq1G2rq97yT31MJxoq+yRQpfcfFbnd3ikE5NhMUI0mtTGqvKYAAGwbt4qRsxZHX8nkROlwL+IUZTt8Ma2c08ej9t3cg9CpXEjXxuYA=

jdk:
- oraclejdk8
install:
- mvn clean install -Dgpg.skip=true -DskipTests=true -P !build-extras -B -V
- mvn install -pl tika-core -am -Dgpg.skip=true
- mvn install -pl tika-parsers -am -Dgpg.skip=true
before_script: 
- "./cd/do-nothing.sh"
cache:
  directories:
  - "~/.m2/repository"
after_success:
- "./cd/before-deploy.sh"
- "./cd/deploy.sh"
after_failure:
- cat com.github.lafa.logfast/target/surefire-reports/*.txt
- cat com.github.lafa.logfast/core/target/surefire-reports/*.txt
